name: my_gtfs_app
channels:
  - conda-forge
  - defaults
dependencies:
  # Force a stable Python version
  - python=3.9 
  
  # KEEP ONLY GEOSPATIAL CORE HERE - these MUST be conda-forge
  - geopandas
  
  # ALL OTHER PACKAGES GO TO PIP
  - pip:
    - streamlit
    - requests
    - pandas
    - geocoder
    - protobuf
    - streamlit-folium
    # CRITICAL: Use the PyPI package name directly here
    - gtfs-realtime-pb2
