name: my_gtfs_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9 
  - streamlit
  - requests
  - pandas
  - geopandas
  - geocoder
  - protobuf
  - python-gtfs-realtime-bindings 
  - pip:
    - streamlit-folium
