name: my_gtfs_app
channels:
  - conda-forge
  - defaults
dependencies:
  # Force a stable Python version (3.9 or 3.10) for compatibility
  - python=3.9 
  # Core Conda-Forge packages for stability
  - streamlit
  - requests
  - pandas
  - geopandas
  - geocoder
  - protobuf
  
  # Use the pip section for the GTFS library and the Streamlit component
  - pip:
    # This is the actual PyPI package name that provides the 'google.transit' module
    - gtfs-realtime-pb2 
    - streamlit-folium
